//
//  CloudLogicAPIFactory.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.13
//

import Foundation
import AWSCore

class CloudLogicAPIFactory {
    static var supportedCloudLogicAPIs: [CloudLogicAPI] {
        
        return [
            CloudLogicAPI(displayName: "mytouristspiderbacon",
                apiDescription: "",
                paths: [
                 "/objects", "/objects/123",                ],
                endPoint: "https://41726x8z8l.execute-api.eu-west-1.amazonaws.com/Development",
                apiClient: AWSAPI_41726X8Z8L_MytouristspiderbaconMobileHubClient(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
        ]
    }
}
