//
//  MainViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.13
//

import UIKit
import AWSMobileHubHelper

class MainViewController: UITableViewController {
    
    var demoFeatures: [DemoFeature] = []
    fileprivate let loginButton: UIBarButtonItem = UIBarButtonItem(title: nil, style: .done, target: nil, action: nil)
    
    fileprivate let tutorialButton: UIBarButtonItem = UIBarButtonItem(title: nil, style: .done, target: nil, action: nil)
    
    // MARK: - View lifecycle
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        if (AWSSignInManager.sharedInstance().isLoggedIn) {
            self.setupBarButtonItem()
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setupBarButtonItem()
        
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back", style: .plain, target: nil, action: nil)
        
        // Default theme settings.
        navigationController!.navigationBar.backgroundColor = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
        navigationController!.navigationBar.barTintColor = UIColor(red: 0xF5/255.0, green: 0x85/255.0, blue: 0x35/255.0, alpha: 1.0)
        navigationController!.navigationBar.tintColor = UIColor.white

        
        var demoFeature = DemoFeature.init(
            name: NSLocalizedString("User Sign-in",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("Enable user login with popular 3rd party providers.",
                comment: "Description for demo menu option."),
            icon: "UserIdentityIcon", storyboard: "UserIdentity", type: "aws")
        
        demoFeatures.append(demoFeature)

        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Cloud Logic",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("Run business logic in the cloud without managing servers. Integrate functionality with your app using APIs.",
                comment: "Description for demo menu option."),
            icon: "CloudLogicAPIIcon", storyboard: "CloudLogicAPI", type: "aws")
        
        demoFeatures.append(demoFeature)
        
        //@Andre
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Tutorial beggin",
                                    comment: "Label for tutorial view"),
            detail: NSLocalizedString("See the app tutorial for new users",
                                      comment: "Tutorial app."),
            icon: "UserIcon", storyboard: "AppTutorial", type: "spiderbacon")
        
        demoFeatures.append(demoFeature)
        
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Tutorial inside app",
                                    comment: "Label for tutorial view"),
            detail: NSLocalizedString("See the app tutorial for current users",
                                      comment: "Tutorial app."),
            icon: "UserIcon", storyboard: "AppTutorial", type: "spiderbacon")
        
        demoFeatures.append(demoFeature)
        
        if (AWSSignInManager.sharedInstance().isLoggedIn) {
            //account settings
            demoFeature = DemoFeature.init(
                name: NSLocalizedString("Account settings",
                                        comment: "Label for account settings view"),
                detail: NSLocalizedString("User account settings",
                                          comment: "Tutorial app."),
                icon: "UserIcon", storyboard: "AccountSettings", type: "spiderbacon")
            
            demoFeatures.append(demoFeature)
        }
        if !(AWSSignInManager.sharedInstance().isLoggedIn) {
            demoFeature = DemoFeature.init(
                name: NSLocalizedString("Sign in",
                                        comment: "Label for sign in view"),
                detail: NSLocalizedString("Sign in to app",
                                          comment: "Sign in."),
                icon: "UserIcon", storyboard: "SignIn", type: "spiderbacon")
            
            demoFeatures.append(demoFeature)
        }

    }

    
    
    func setupBarButtonItem() {
        navigationItem.rightBarButtonItem = loginButton
        navigationItem.rightBarButtonItem!.target = self
        
        //@Andre
        //use on navbar events page
        //mete um ou o outro icon
        
        if (AWSSignInManager.sharedInstance().isLoggedIn) {
            navigationItem.rightBarButtonItem!.title = NSLocalizedString("Sign-Out", comment: "Label for the logout button.")
            navigationItem.rightBarButtonItem!.action = #selector(MainViewController.handleLogout)
        }
        if !(AWSSignInManager.sharedInstance().isLoggedIn) {
            navigationItem.rightBarButtonItem!.title = NSLocalizedString("Sign-In", comment: "Label for the login button.")
            navigationItem.rightBarButtonItem!.action = #selector(goToLogin)
        }
        
    }
    

    // MARK: - UITableViewController delegates
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "MainViewCell")!
        let demoFeature = demoFeatures[indexPath.row]
        cell.imageView!.image = UIImage(named: demoFeature.icon)
        cell.textLabel!.text = demoFeature.displayName
        cell.detailTextLabel!.text = demoFeature.detailText
        return cell
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return demoFeatures.count
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
        tableView.deselectRow(at: indexPath, animated: true)
        let demoFeature = demoFeatures[indexPath.row]
        let storyboard = UIStoryboard(name: demoFeature.storyboard, bundle: nil)
        let viewController = storyboard.instantiateViewController(withIdentifier: demoFeature.storyboard)
        
        //@Andre
        if(demoFeature.type == "spiderbacon") {
            self.present(viewController, animated: true, completion: nil)
        } else {
            self.navigationController!.pushViewController(viewController, animated: true)
        }
        
    }

    func goToLogin() {
            print("Handling optional sign-in.")
            let loginStoryboard = UIStoryboard(name: "SignIn", bundle: nil)
            let loginController = loginStoryboard.instantiateViewController(withIdentifier: "SignIn")
            navigationController?.pushViewController(loginController, animated: true)
    }
    
    func handleLogout() {
        print("ogout")
        
        if (AWSSignInManager.sharedInstance().isLoggedIn) {
            AWSSignInManager.sharedInstance().logout(completionHandler: {(result: Any?, authState: AWSIdentityManagerAuthState, error: Error?) in
                self.navigationController!.popToRootViewController(animated: false)
                self.setupBarButtonItem()
            })
            // print("Logout Successful: \(signInProvider.getDisplayName)");
        } else {
            assert(false)
        }
    }
}

class FeatureDescriptionViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem.init(title: "Back", style: .plain, target: nil, action: nil)
    }
}
