//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.13
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "eu-west-1_fESAzxsfG"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "1dg6l7u087ivr90fhp6bmgdl4h"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .EUWest1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "arbvnvno8k9no1tub46qkl4h455s72i1bt9n9cgsan44m6r2tua"

// Identifier for Cloud Logic API invocation clients
let AWSCloudLogicDefaultConfigurationKey: String = "CloudLogicAPIKey"
let AWSCloudLogicDefaultRegion: AWSRegionType = .EUWest1
